services:
  nginx:
    build: ./nginx/
    ports:
      - 8080:80

    volumes:
      - ./php/:/var/www/html/

  php:
    build: ./php/
    expose:
      - 9000

    volumes:
      - ./php/:/var/www/html/

  db:
    image: mariadb
    volumes:
      - ./pbl-data:/var/lib/mysql
      - ./script:/docker-entrypoint-initdb.d 

    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: pbl01_db
      MYSQL_USER: pbl01_user
      MYSQL_PASSWORD: pbl01_user_pass
    ports:
      - 6033:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
